### ISSUE TITLE
Popover is broken

### ISSUE THREAD

**Issue by justvanrossum** [robotools/vanilla#104]
```python
from vanilla import Popover
p = Popover((10, 10, 200, 300))
```

```
/Users/just/code/git/vanilla/Lib/vanilla/vanillaPopover.py:123: UninitializedDeallocWarning: leaking an uninitialized object of type VVanillaPopoverContentView
  self._nsObject = getNSSubclass(self.contentViewClass).alloc().initWithFrame_(((0, 0), size))
Traceback (most recent call last):
  File "<untitled>", line 2, in <module>
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaPopover.py", line 123, in __init__
    self._nsObject = getNSSubclass(self.contentViewClass).alloc().initWithFrame_(((0, 0), size))
objc.internal_error: Cannot calculate FFI type for {CGRect={CGPoint=dd}{CGSize=dd}}16
Exception ignored in: <bound method Popover.__del__ of <vanilla.vanillaPopover.Popover object at 0x10a433e80>>
Traceback (most recent call last):
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaPopover.py", line 139, in __del__
    self._breakCycles()
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaPopover.py", line 143, in _breakCycles
    view = self._getContentView()
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaBase.py", line 131, in _getContentView
    return self._nsObject
AttributeError: 'Popover' object has no attribute '_nsObject'
```

**Comment by justvanrossum** [comment]
I'm getting a different error in my actual app, trying to reproduce.

**Comment by justvanrossum** [comment]
Sorry, the above code is bogus. Will further search later.

**Comment by justvanrossum** [comment]
This is the actual traceback:
```
Traceback (most recent call last):
  File "myCode.py", line 175, in buttonClick
    self.featurePopover = p = Popover((170, height + 20))
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaGroup.py", line 86, in __setattr__
    super(Group, self).__setattr__(attr, value)
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaBase.py", line 48, in __setattr__
    _setAttr(VanillaBaseObject, self, attr, value)
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaBase.py", line 357, in _setAttr
    if hasattr(value, "getPosSize") and value.getPosSize() == "auto":
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaBase.py", line 157, in getPosSize
    return self._posSize
AttributeError: 'Popover' object has no attribute '_posSize'
```

But I am not yet successful in creating a small reproducer. Although: now I see, the `self` in my code is a `Group` instance, so perhaps that should be a clue.

**Comment by justvanrossum** [comment]
The intent of `self.featurePopover` was to have a reference to the Popover, and that used to be no problem. If I make sure I don't assign a Popover instance to an attribute of my Group subclass, it works. 

Maybe that code was never kosher, but it did work. Let me try to find what changed.

**Comment by justvanrossum** [comment]
Ok, the change was introduced in the autolayout PR:

https://github.com/robotools/vanilla/blob/9e8cb5f6b0aca2542647157fa68ca71078507586/Lib/vanilla/vanillaBase.py#L357

Popover _does_ implement `getPosSize()` because it inherits it from VanillaBaseObject, but it doesn't work:

```python
from vanilla import Popover
p = Popover((100, 200))
p.getPosSize()
```

```
Traceback (most recent call last):
  File "<untitled>", line 3, in <module>
  File "/Users/just/code/git/vanilla/Lib/vanilla/vanillaBase.py", line 157, in getPosSize
    return self._posSize
AttributeError: 'Popover' object has no attribute '_posSize'
```

That should not be a problem, as I don't think Popover needs getPosSize() really. My code assigns a Popover instance to an attribute of a Group subclass, which is perhaps a little sneaky, as all I need is a reference to the popup, but now this is interfering with the vanilla setattr behavior.

I can't really blame vanilla, so I'll just work around it in my code.

**Comment by typemytype** [comment]
I think you touch a number of edge cases with a Popover

* it should clean up nicely in `_breakCycles`
* a `getPosSize` and `setPosSize` would be a good thing, similar to a `Window` or `Sheet` object. A Popover is basically the same as a Window.

**Comment by justvanrossum** [comment]
> it should clean up nicely in _breakCycles

It could be that that error was triggered by me (in my first bogus example) not calling Popover with the correct argument: like Window, it wants a (w, h) tuple, not a (x, y, w, h) tuple. Fix that and the `_breakCycles` error disappears.

**Comment by typemytype** [comment]
you need to keep a reference somewhere of the NSPopover object, if not this pops up: `UninitializedDeallocWarning: leaking an uninitialized object of type VVanillaPopoverContentView` and will mess up everything afterwards

**Comment by typemytype** [comment]
maybe a Popover shouldn't by a subclass of a VanillaBaseObject but similar to a Window be a subclass of a NSObject with vanilla like attributes like getPosSize and others
