### ISSUE TITLE
assigning "minimalistic" colorWellStyle to ColorWell crashes the program

### ISSUE THREAD

**Issue by RafalBuchner** [robotools/vanilla#189]
I'm reciving this error (python 3.11.3).
my args and kwargs looks like this:

args = ("auto",)
kwargs = dict(callback=self.objCallback, color=color, colorWellStyle="minimal")

```
Traceback (most recent call last):
  File "~/source/code/testSettings.py", line 164, in <module>
    executeVanillaTest(GridViewExample)
  File "~/venvs/fontenv/lib/python3.11/site-packages/vanilla/test/testTools.py", line 59, in executeVanillaTest
    cls(**kwargs)
  File "/Users/rafalbuchner/__work__/++repos++/__my_repos__/curvatureVisualizator/source/code/testSettings.py", line 105, in __init__
    obj = ColorWell(*args,**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/venvs/fontenv/lib/python3.11/site-packages/vanilla/vanillaColorWell.py", line 78, in __init__
    colorPanel.setColorWellStyle_(nsColorWellStyle)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by RafalBuchner** [comment]
ok, My vanilla version wasn't set to latest dev build

**Comment by typemytype** [comment]
Yeah the pip release is behind..

**Comment by benkiel** [comment]
FYI, new release pushed to pip, v0.4.0
