### ISSUE TITLE
Validate menu items in List contextual menu.

### ISSUE THREAD

**Issue by typesupply** [robotools/vanilla#78]
It would be nice to show/hide specific items in a contextual  menu in List. Here's a proposal for doing that.

In `List`:

```python
def setMenu_(self, items, validator=None):
    self._menuItemValidator = validator
    self._callbackWrappers = []
    ...
```

In `VanillaTableViewSubclass`:

```python
def menuForEvent_(self, event):
    wrapper = self.vanillaWrapper()
    if wrapper._menu is not None:
        if wrapper._menuItemValidator is not None:
            self._validateMenu(wrapper, wrapper._menu)
        return wrapper._menu

def _validateMenu(self, wrapper, menu):
    # XXX this is untested pseudo-code
    for item in menu.itemArray():
        if item == NSMenuItem.separatorItem():
            pass
        elif isinstance(item, NSMenu):
            self._validateMenu(wrapper, item)
        else:
            self._validateMenuItem(wrapper, item)

def _validateMenuItem(self, wrapper, item):
    hidden = not wrapper._menuItemValidator(wrapper, item.title())
    item.setHidden_(hidden)
```

The validator function would look like this:

```python
def myValidator(vanillaList, itemTitle):
    if title == "foo":
        if blah.blah.blah:
            return False
    return True
```

If `True` is returned, show the item. If `False` is returned, don't show the item.

**Comment by typesupply** [comment]
Thinking about the value returned by the validation function… It should return more verbose descriptions than `True` and `False` to enable more behaviors.

- show
- hide
- enable
- disable

Perhaps a list of values instead of a single value.

**Comment by typesupply** [comment]
If we want to only enable validation of one particular item, we could add a "validator" to the menu item description used to construct the menu in `List.setMenu`.

```python

item["validator"] = myItemValidator

def myItemValidator(self):
    if blah.blah.blah:
        return "hide"
    return "show"
```

This could be annoying if many items need to be validated, but that is an edge case.

From an implementation standpoint, the same menu constructor is used for List, PopUpButton, etc. Should menus other than List allow validation? That's going to require a bit more work.

**Comment by typemytype** [comment]
mmm, maybe we should reverse how to set menu for list:

think as a callback whenever a user interaction requires a menu:

```python
def callback(sender):
    print("menu callback")
    
def myMenuCallback(sender):
    # you want to make the menu contextual based on fe a selection
    sel = sender.selection()
    if sel:        
        return [("My Title", callback)]
    return None # no menu
   
# very similar api as for selectionCallback or doubleClickCallback
List((10, 10, -10, -10), menuCallback=myMenuCallback)
```

(the current setMenu could be deprecated) 

cc @letterror

**Comment by LettError** [comment]
This would allow effective contextual menus because `myMenuCallback` can respond to the contents of the list and any other external factors.

**Comment by typemytype** [comment]
example:

```python

import vanilla
import random

class ListMenuController(object):
    
    def __init__(self):
        self.w = vanilla.Window((400, 600))
        
        self.w.l1 = vanilla.List((0, 0, 0, 200), ["a", "b"])

        self.w.l2 = vanilla.List((0, 200, 0, 200), ["a", "b"])
        
        self.w.l2.setMenu(
            [dict(title="Title", callback=self.dummyCallback), ]
        )
        
        self.w.l3 = vanilla.List((0, 400, 0, 200), ["a", "b", "c", "d"], menuCallback=self.menuCallback)
        
        self.w.open()
    
    def dummyCallback(self, sender):
        print(sender)
    
    def menuCallback(self, sender):
        sel = sender.getSelection()
        items = [
            dict(title=random.choice(sender), callback=self.dummyCallback)
        ]        
        for i in sel:
            items.append(dict(title="do something for '%s'" % sender[i], callback=self.dummyCallback))

        return items

        
ListMenuController()
```

**Comment by LettError** [comment]
This could happen:
```python
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 97, in sendEvent_
  File "/Users/erik/code/vanilla/Lib/vanilla/vanillaList.py", line 38, in menuForEvent_
    return wrapper._menuForEvent(event)
  File "/Users/erik/code/vanilla/Lib/vanilla/vanillaList.py", line 915, in _menuForEvent
    return menu
UnboundLocalError: local variable 'menu' referenced before assignment
```

See line 915, commented: https://github.com/typesupply/vanilla/commit/46888a917d81760b444993f52789f9a077c3fd54#r30309584

**Comment by LettError** [comment]
Problem while making submenus:
`TypeError: VanillaMenuBuilder() missing 1 required positional argument: 'menu'`

Can be fixed with in https://github.com/typesupply/vanilla/blob/master/Lib/vanilla/vanillaList.py#L231:
```python
             if subItems:
                 subMenu = NSMenu.alloc().init()
-                VanillaMenuBuilder(subItems, subMenu)
+                VanillaMenuBuilder(sender, subItems, subMenu)
                 menuItem.setSubmenu_(subMenu)
```

**Comment by typesupply** [comment]
I'm closing this since it is related to the soft-deprecated `List`. If it still applies to `List2` please reopen the issue and tag me.
